package studylog;
import javax.swing.*;
import java.io.*;
import java.util.Scanner;
import java.util.List;


/*
 *Hello all. Prepare to get cancer from this terrible coding :)
 */

/**
 *
 * @author Dylan
 */
public class MainGUI extends javax.swing.JFrame {
    String logFile = "Log.txt"; //Change this if you want to change the log file name.
    
    int Time;
    int DTotal;
    int DHours;
    int DMinutes;
    
    int JHours;
    int JMinutes;
    int JTotal;
    
    int WHours;
    int WMinutes;
    int WTotal;
    
    int KHours;
    int KMinutes;
    int KTotal;
        
    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        
        initComponents();
        SetLabels();
        setSize(1010, 635);
        setResizable(false);
        if (!GetData.checkFileExists(logFile)) {
            System.out.println("File not found. Regenerating...");
            GetData.regenFile(logFile);
        }
        rewriteData();
        
        
    }
    public void rewriteData() { //Regenerate names if not found
        //Add names here.
        String[] names = {"Dylan", "Jack", "Weilon", "Katrina"};
        String checkExistingData = "";
        for (int i = 0; i < names.length; i++) {
            checkExistingData = GetData.getTime(names[i]);
            if (checkExistingData == null) {
                GetData.write(logFile, names[i], "0");
            }
        }
    }
    public void SetLabels() {
       DTotal = GetData.getTimeDylan();
       DHours = DTotal/60;
       DMinutes = (DTotal - DHours*60);
       lblDylanTime.setText(DHours+" Hour(s), "+DMinutes+" Minutes");
       
       JTotal = GetData.getTimeJack();
       JHours = JTotal/60;
       JMinutes = (JTotal - JHours*60);
       lblJackTime.setText(JHours+" Hour(s), "+JMinutes+" Minutes");
        
       WTotal = GetData.getTimeWeilon();
       WHours = WTotal/60;
       WMinutes = (WTotal - WHours*60);
       lblWhaleTime.setText(WHours+" Hour(s), "+WMinutes+" Minutes");
       
       KTotal = GetData.getTimeKatrina();
       KHours = KTotal/60;
       KMinutes = (KTotal - KHours*60);
       lblKatrinaTime.setText(KHours+" Hour(s), "+KMinutes+" Minutes");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNAME = new javax.swing.JTextField();
        txtTIME = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblWinning = new javax.swing.JLabel();
        lblDylan1 = new javax.swing.JLabel();
        lblKatrinaTime = new javax.swing.JLabel();
        lblDylan = new javax.swing.JLabel();
        lblDylanTime = new javax.swing.JLabel();
        lblWhale = new javax.swing.JLabel();
        lblWhaleTime = new javax.swing.JLabel();
        lblJack = new javax.swing.JLabel();
        lblJackTime = new javax.swing.JLabel();
        lblWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        txtNAME.setFont(new java.awt.Font("Helvetica-Narrow", 0, 36)); // NOI18N
        getContentPane().add(txtNAME);
        txtNAME.setBounds(80, 100, 390, 54);

        txtTIME.setFont(new java.awt.Font("Helvetica-Narrow", 0, 36)); // NOI18N
        txtTIME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTIMEActionPerformed(evt);
            }
        });
        getContentPane().add(txtTIME);
        txtTIME.setBounds(80, 210, 390, 54);

        jButton1.setFont(new java.awt.Font("Helvetica-Narrow", 0, 24)); // NOI18N
        jButton1.setText("Submit Times");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(80, 270, 390, 80);

        jLabel2.setFont(new java.awt.Font("Helvetica-Narrow", 0, 24)); // NOI18N
        jLabel2.setText("Time (in minutes):");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 160, 392, 44);

        jLabel4.setFont(new java.awt.Font("Helvetica-Narrow", 0, 24)); // NOI18N
        jLabel4.setText("First Name:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 50, 392, 44);

        lblWinning.setFont(new java.awt.Font("Helvetica-Narrow", 0, 24)); // NOI18N
        lblWinning.setText("Currently in the lead is:");
        getContentPane().add(lblWinning);
        lblWinning.setBounds(100, 360, 360, 44);

        lblDylan1.setFont(new java.awt.Font("Helvetica-Narrow", 0, 24)); // NOI18N
        lblDylan1.setText("Katrina");
        getContentPane().add(lblDylan1);
        lblDylan1.setBounds(530, 200, 80, 44);

        lblKatrinaTime.setFont(new java.awt.Font("Helvetica-Narrow", 0, 24)); // NOI18N
        lblKatrinaTime.setText("___________________");
        getContentPane().add(lblKatrinaTime);
        lblKatrinaTime.setBounds(620, 200, 290, 44);

        lblDylan.setFont(new java.awt.Font("Helvetica-Narrow", 0, 24)); // NOI18N
        lblDylan.setText("Dylan");
        getContentPane().add(lblDylan);
        lblDylan.setBounds(530, 50, 80, 44);

        lblDylanTime.setFont(new java.awt.Font("Helvetica-Narrow", 0, 24)); // NOI18N
        lblDylanTime.setText("___________________");
        getContentPane().add(lblDylanTime);
        lblDylanTime.setBounds(620, 50, 310, 44);

        lblWhale.setFont(new java.awt.Font("Helvetica-Narrow", 0, 24)); // NOI18N
        lblWhale.setText("Weilon");
        getContentPane().add(lblWhale);
        lblWhale.setBounds(530, 150, 80, 44);

        lblWhaleTime.setFont(new java.awt.Font("Helvetica-Narrow", 0, 24)); // NOI18N
        lblWhaleTime.setText("___________________");
        getContentPane().add(lblWhaleTime);
        lblWhaleTime.setBounds(620, 150, 300, 44);

        lblJack.setFont(new java.awt.Font("Helvetica-Narrow", 0, 24)); // NOI18N
        lblJack.setText("Jack");
        getContentPane().add(lblJack);
        lblJack.setBounds(530, 100, 60, 44);

        lblJackTime.setFont(new java.awt.Font("Helvetica-Narrow", 0, 24)); // NOI18N
        lblJackTime.setText("___________________");
        getContentPane().add(lblJackTime);
        lblJackTime.setBounds(620, 100, 300, 44);

        lblWallpaper.setFont(new java.awt.Font("Helvetica-Narrow", 0, 24)); // NOI18N
        lblWallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studylog/Wallpaper.png"))); // NOI18N
        getContentPane().add(lblWallpaper);
        lblWallpaper.setBounds(0, 0, 1000, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTIMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTIMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTIMEActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      String Currentname = txtNAME.getText();
        if ("dylan".equalsIgnoreCase(Currentname)) {
             Time = GetData.getTimeDylan();
             System.out.println(Time);
             Time = Time + getTextboxTime();
             GetData.setTimeDylan(Time);
             System.out.println(Time);
        }
        else if ("weilon".equals(Currentname)) {
             Time = GetData.getTimeWeilon();
             System.out.println(Time);
             Time = Time + getTextboxTime();
             GetData.setTimeWeilon(Time);
             System.out.println(Time);
        }
        else if ("jack".equals(Currentname)) {
             Time = GetData.getTimeJack();
             System.out.println(Time);
             Time = Time + getTextboxTime();
             GetData.setTimeJack(Time);
             System.out.println(Time);
        }
        else if ("katrina".equals(Currentname)) {
             Time = GetData.getTimeKatrina();
             System.out.println(Time);
             Time = Time + getTextboxTime();
             GetData.setTimeKatrina(Time);
             System.out.println(Time);
        }
        else {
            JOptionPane.showMessageDialog(null, "Enter your name correctly!");
        }
        txtTIME.setText("");
        SetLabels(); 
    }//GEN-LAST:event_jButton1ActionPerformed

    public int getTextboxTime() {
        int intTime = 0;
        try {
            String stringTime = txtTIME.getText();
            intTime = Integer.parseInt(stringTime);
        }
        catch (NumberFormatException e) {
            intTime = 0;
            
        }
        finally {
            if (intTime == 0) {
                JOptionPane.showMessageDialog(null, "Enter a valid number", "Error", JOptionPane.ERROR_MESSAGE);
            }
            System.out.println("Time = " + intTime);
            return intTime;
            
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblDylan;
    private javax.swing.JLabel lblDylan1;
    private javax.swing.JLabel lblDylanTime;
    private javax.swing.JLabel lblJack;
    private javax.swing.JLabel lblJackTime;
    private javax.swing.JLabel lblKatrinaTime;
    private javax.swing.JLabel lblWallpaper;
    private javax.swing.JLabel lblWhale;
    private javax.swing.JLabel lblWhaleTime;
    private javax.swing.JLabel lblWinning;
    private javax.swing.JTextField txtNAME;
    private javax.swing.JTextField txtTIME;
    // End of variables declaration//GEN-END:variables
}
