/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package studylog;

/**
 *
 * @author Weilon
 */
public class Rules extends javax.swing.JDialog {

    /**
     * Creates new form Rules
     */
    public Rules(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGUI = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblRule1 = new javax.swing.JLabel();
        lblRule2 = new javax.swing.JLabel();
        lblRule3 = new javax.swing.JLabel();
        lblRule3_1 = new javax.swing.JLabel();
        lblRule4 = new javax.swing.JLabel();
        lblRule5 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setText("Rules");

        lblRule1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRule1.setText("1. Don't make up times. ");

        lblRule2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRule2.setText("2. School and tutoring does not count. ");

        lblRule3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRule3.setText("3. Homework and assignments do count, as the");

        lblRule3_1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRule3_1.setText("amount of time taken will vary depending on effort.");

        lblRule4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRule4.setText("4. Breaks do not count* ");

        lblRule5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblRule5.setText("*[10:27:04 PM] Jack Qu: how about eating food");

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGUILayout = new javax.swing.GroupLayout(panelGUI);
        panelGUI.setLayout(panelGUILayout);
        panelGUILayout.setHorizontalGroup(
            panelGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGUILayout.createSequentialGroup()
                .addGroup(panelGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGUILayout.createSequentialGroup()
                        .addGroup(panelGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelGUILayout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addComponent(lblTitle))
                            .addGroup(panelGUILayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(panelGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRule2)
                                    .addComponent(lblRule1)
                                    .addComponent(lblRule3)
                                    .addComponent(lblRule4)))
                            .addGroup(panelGUILayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(lblRule3_1)))
                        .addGap(0, 66, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGUILayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblRule5)))
                .addContainerGap())
        );
        panelGUILayout.setVerticalGroup(
            panelGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGUILayout.createSequentialGroup()
                .addGroup(panelGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelGUILayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelGUILayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblTitle)
                        .addGap(18, 18, 18)
                        .addComponent(lblRule1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRule2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRule3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRule3_1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRule4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addComponent(lblRule5)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGUI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGUI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Rules dialog = new Rules(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel lblRule1;
    private javax.swing.JLabel lblRule2;
    private javax.swing.JLabel lblRule3;
    private javax.swing.JLabel lblRule3_1;
    private javax.swing.JLabel lblRule4;
    private javax.swing.JLabel lblRule5;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panelGUI;
    // End of variables declaration//GEN-END:variables
}
